name: Contrib

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile admin/halog/halog
      run: |
        make admin/halog/halog
    - name: Compile dev/flags/flags
      run: |
        make dev/flags/flags
    - name: Compile dev/poll/poll
      run: |
        make dev/poll/poll
    - name: Compile dev/hpack
      run: |
        make dev/hpack/decode dev/hpack/gen-enc dev/hpack/gen-rht
